# Training Configuration
# resume_weights_path: "/path/to/pretrained/model.pth"
resume_weights_path: null
resume_start_with_eval: false
log_frequency: 100
eval_each_epoch: 1 # 0 is disabled - otherwise run eval every N epochs
ckpt_dir: "checkpoints"
epoch_st: 1
epochs_end: 50
fast_forward_scheduler: false
max_samples: 0 # 0 means use all samples

# Comet ML Configuration (Optional - for experiment tracking)
# Sign up for free at https://www.comet.com/ to get your API key
comet_ml_enable: false
comet_ml_api_key: "YOUR_COMET_API_KEY_HERE"  # Get from https://www.comet.com/api/my/settings
comet_ml_workspace: "YOUR_WORKSPACE_NAME"     # Your Comet ML workspace
comet_ml_project_name: "birefnet"

# Upscaling Configuration (for inference_upscale.py)
# Path to RealESRGAN model weights (x2 or x4)
# Download from: https://github.com/ai-forever/Real-ESRGAN
upscale_model_path: "weights/RealESRGAN_x2.pth"  # or RealESRGAN_x4.pth